name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"                          # KV绑定名默认不可修改
id = "d959bd2be3234f48bca10accd3167b50" # KV数据库id (fragrant-wood-74f6-KV)